---  
- name: Install VsCode version "{{ vscode_version }}" & start custom code tunnel
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: vscode_tunnel_name #variable
      prompt: "Enter the name for the Visual Studio Code tunnel: "
      private: false
  roles: 
    - stop_vscode_tunnels_role
